// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Game
{
	public class Edge
	{
		readonly Tile m_parentTile;
		List <Segment> m_segments;
		EdgeType m_type;

		public enum EdgeType
		{
			EDGE_TOP,
			EDGE_RIGHT,
			EDGE_BOTTOM,
			EDGE_LEFT,
			MAX_EDGES = EDGE_LEFT
		}

		public Edge(Tile parentTile, EdgeType type)
		{
			m_parentTile = parentTile;
			m_type = type;
			m_segments = new List<Segment>(3);
		}

		public void SetSegment(int segIdx, Segment seg)
		{
			m_segments[segIdx] = seg;
		}

		public EdgeType GetEdgeType()
		{
			return m_type;
		}
	}
}

