// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace Game
{
	public class FeatureSegment
	{
		int m_id;
		FeatureType m_type;
		Vector2 m_placementPos;
		bool m_occupied;


		public enum FeatureType
		{
			DOCK,
			ISLAND,
			LIGHTHOUSE,
			WATER
		}

		public FeatureSegment (int id, FeatureType type, Vector2 pos)
		{
			m_id = id;
			m_type = type;
			m_placementPos = pos;
			m_occupied = false;
		}

		public int GetId()
		{
			return m_id;
		}

		public void SetOccupied(bool occupied)
		{
			m_occupied = occupied;
		}

		public void PrintInfo()
		{
			Debug.Log("    Feature segment id - " + m_id + ", type - " + m_type + ", pos - (" + m_placementPos.x + ", " + m_placementPos.y + ")");
		}
	}
}

