// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Game
{
	public class Segment
	{
		Feature m_feature;
		int m_id;

		public Segment (Feature.FeatureType featureType, int id)
		{
			m_feature = new Feature(featureType);
			m_id = id;
		}
	}
}

