// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Xml;

namespace Game
{
	public class XMLReader
	{
		public static XmlDocument Read(string fileName)
		{
			XmlDocument doc = new XmlDocument();
			doc.Load(fileName+".xml");
			return doc;
		}
	}
}

